"""

Revision ID: dde62e8187d5
Revises: bb4c59834853
Create Date: 2025-08-11 17:21:34.636438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde62e8187d5'
down_revision = 'bb4c59834853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_signal',
    sa.Column('fuserid', sa.Integer(), nullable=True),
    sa.Column('fword', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fstatus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fuserid'], ['tbl_users.id'], name=op.f('fk__tbl_signal__fuserid__tbl_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__tbl_signal')),
    sa.UniqueConstraint('id', name=op.f('uq__tbl_signal__id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_signal')
    # ### end Alembic commands ###
